### ISSUE TITLE
Clearing click or box search results

### ISSUE THREAD

**Issue by davidheyman** [axismaps/rice#145]
@bcsheesley Can you take a look at how you exit search results that appear by clicking the map or by the box search? I'm concerned it's not immediately apparent that to return to the legend after you've clicked the map you need to hit the X next to an empty search field.

Ideally we'd come up with something that works with a text search as well, but that's not necessary.

**Comment by bcsheesley** [comment]
@davidheyman I had been thinking the same thing here: https://github.com/axismaps/rice/issues/142. I We probably need a button to clear those results.

**Comment by davidheyman** [comment]
I think this needs 2 small revisions:

1. The X icon is awkwardly placed. Moving it to the left of the text and giving it some space should make it read better
2. The button needs some white space around it, otherwise it gets lost in the darker gray headers

Not sure what you've tried and abandoned already, but could we do some kind of *Back to legend* button that could be present for both text and map searches? I think some consistency would help AND more users will be asking *How do I get back to the legend?* instead of *How do I clear this search?*

**Comment by bcsheesley** [comment]
The top row shows text search. The second row shows three options for geo search. In terms of consistency, I think all three would all be an improvement.

I'm not sure if: 1) it's important to have text search available when geo search results appear, and 2) how feasible it is to count geo search results. Maybe option three is the simplest? Instead of "Back" we could say "Map legend", although we don't refer to it as such anywhere else.

Thoughts @davidheyman ?

![searches](https://user-images.githubusercontent.com/4501388/40525428-8f8589c2-5fa5-11e8-91a3-17cbb7bda2a2.png)

**Comment by davidheyman** [comment]
I agree about option 3, with 2 small changes:

1. Make the text say "Back to legend". Novice map readers are all about legends and knowing about legends (not joking).

2. Maybe we could boost that back icon a little bit with a circle or square border like this -> https://fontawesome.com/icons/arrow-circle-left?style=regular. Not sure if it would conflict with the year steppers above though...

**Comment by bcsheesley** [comment]
@bwellington Just re-posting what we had talked about in Slack. This is "option 3", now with a stronger back arrow button and static text (italic), not to be confused with the "Search map layers..." text which is, in fact, a separate button.

![option3](https://user-images.githubusercontent.com/4501388/40846573-9e75bd82-657f-11e8-8e9b-5d756e794d9a.png)
