### ISSUE TITLE
Animated transitions on era steppers

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/rice#24]
What do you think about this content sliding in/out to the left and right? I think it could help with orientation in time, given we don't have a graphic indicator besides the date stamp.

![instituterice](https://user-images.githubusercontent.com/4501388/32289522-f380cadc-bf04-11e7-9ea9-67c61b468bd2.png)

In addition, I'm wondering about a transition for the thumbnail filmstrip below to make it clear that its content is linked to the era you've just stepped to. I'm not sure the loading indicators on each thumb are enough.

Should the whole filmstrip panel close and open with each step? Should a new panel slide upward and replace the existing? Should the thumbnails follow the text above and also slide in/out to the left and right?

**Comment by awoodruff** [comment]
This isn't super smooth, I guess because of all the photo elements being added at the same time, but it's there. As for the filmstrip panel itself, I added the era years to the tab. Maybe that helps?
![screen shot 2017-11-21 at 2 30 59 pm](https://user-images.githubusercontent.com/3533462/33092634-b9c98990-cec8-11e7-9c86-09053361d84e.png)

**Comment by bcsheesley** [comment]
Cool, I like it. It's pretty smooth for me actually. The filmstrip dates are a good, too. Should we also include the year here when you're on the map? Might not hurt, if it isn't too much trouble.
