### ISSUE TITLE
Add place in the legend (top) to turn off the viewcones

### ISSUE THREAD

**Issue by davidheyman** [axismaps/rice#31]
@bcsheesley Can you do a design for this? It's a feature currently in Rio if you need a reference.

**Comment by bcsheesley** [comment]
This should probably go in it's own section called "Views". A little odd, maybe, because it will only have one thing in it ("Cones of vision"), but unlike Rio maps and plans do not appear in the legend.

![rice](https://user-images.githubusercontent.com/4501388/32462623-af24029c-c2ff-11e7-95a8-e40c9b4b65cf.png)
