### ISSUE TITLE
Add new eras

### ISSUE THREAD

**Issue by davidheyman** [axismaps/rice#36]
Eras are available on Airtable and here -> ![eras.xlsx](http://static.gitscout.com/4e553006d92ee3df25de560c162cf8c9a0611e584cce731b119c3d89300b18d5.xlsx)

**Comment by awoodruff** [comment]
@bcsheesley Current designs use different colors for 3 eras on the timeline and intro screen; do you have a suggestion for how to use colors (if at all) for more eras? There are 7 here.

**Comment by bcsheesley** [comment]
Yeah, let's ditch the color-coding. We can still use a gradient to show light-dark / past-future. The gradient can be from the light-blue to the dark-blue color currently in the timeline.

That means means no color chips on the intro screen either. Maybe we go with blue text there? Dividers between eras? I could go either way on styling that group of text buttons or just leaving it as-is.

As for the main timeline, I suppose we still ought to indicate eras in some way. One possibility that isn't too obtrusive is to notch each break-point with half-circle or diamond. Is that doable?

![screen shot 2017-11-15 at 3 24 42 pm](https://user-images.githubusercontent.com/4501388/32861538-9f39b7b0-ca1a-11e7-952c-0cf47ad94a69.png)

![screen shot 2017-11-15 at 3 24 49 pm](https://user-images.githubusercontent.com/4501388/32861544-a1210fe2-ca1a-11e7-9c40-3c63f9d0456c.png)

![window](https://user-images.githubusercontent.com/4501388/32861555-a908c722-ca1a-11e7-874c-d8c7c254da3a.png)

**Comment by awoodruff** [comment]
Thanks Ben. I've left the eras on the intro screen mostly alone, partly as the lazy way, but also because I like it well enough as is. Let me know if you want any changes though.

![screen shot 2017-11-16 at 2 58 24 pm](https://user-images.githubusercontent.com/3533462/32912924-a476fda4-cade-11e7-92f0-317f023dae6f.png)

![screen shot 2017-11-16 at 2 59 48 pm](https://user-images.githubusercontent.com/3533462/32912964-d2366838-cade-11e7-898e-b4e79c951756.png)
