### ISSUE TITLE
Update text on splash screen

### ISSUE THREAD

**Issue by davidheyman** [axismaps/rice#58]
> instituteRice is an online mapping platform that illustrates the evolution of the Rice University campus, as it existed as well as it has often been imagined. Primary sources from the Woodson Research Center (e.g., photographs, historical maps, campus plans) are located temporally and spatially while their associated visual and geographic data is integrated across a an open-access digital library of images, a geographic information system, an open source relational database, and a content delivery web service.

> This product is for informational purposes and was neither prepared nor is suitable for legal, engineering, or surveying purposes. Represented objects have approximate locations relative to a particular moment of the research project. No warranty is made regarding specific accuracy or completeness. Rice University and the instituteRice research team assume no liability or damages due to errors or omissions."

**Comment by awoodruff** [comment]
This is, of course, too long to fit nicely, so I have taken a few liberties with design. Let me know if this stuff seems okay. cc @bcsheesley 

1. Second paragraph (disclaimer stuff) is smaller text
2. Text block is wider (75% now, was 50%). Some minor margin/padding adjustments too. The screenshot below is about as small/tight as can be accommodated now (950ish x 600ish), including a little extra compression for < 700px height.
3. Second screen added to mobile for the overview of eras. The initial "Begin Exploring" button takes you to this instead of the map. No change to desktop behavior.

![screen shot 2017-12-15 at 9 34 31 am](https://user-images.githubusercontent.com/3533462/34046579-89c1eb6e-e17b-11e7-9765-47ad8a5a9d6f.png)

![localhost_8080_ iphone 6](https://user-images.githubusercontent.com/3533462/34046593-9c098dae-e17b-11e7-9587-ae0137fc8105.png)

![localhost_8080_ iphone 6 2](https://user-images.githubusercontent.com/3533462/34046600-a010bb0c-e17b-11e7-87f9-ba55f2b432ca.png)

**Comment by davidheyman** [comment]
My quick suggestion would be to make the disclaimer text even smaller, give it full width, and drop it at the very bottom of the screen below the button.

**Comment by bcsheesley** [comment]
I like it, and agree with Dave's suggestion. The only other thing would be to start hiding some content, like putting the era buttons in a dropdown. But that's a bigger change, so probably best to keep it in our back pocket for now.

![screen shot 2017-12-15 at 12 34 32 pm](https://user-images.githubusercontent.com/4501388/34055340-562bccca-e194-11e7-8783-b3ff0a175082.png)

![screen shot 2017-12-15 at 12 33 31 pm](https://user-images.githubusercontent.com/4501388/34055346-5eed7674-e194-11e7-843d-6319a2d28426.png)

**Comment by davidheyman** [comment]
I just tested this on an iPhone 8 and the disclaimer text obscures the button so it can't be clicked. I tried some other iPhones on Browserstack and those buttons couldn't be clicked either but I didn't notice the text overlapping.

![bs_realios_Mobile_iPhone 8-11.0](http://static.gitscout.com/e81bdd2c602f6210491de42a65c25c04d95c852ac55e99cdd9b72da6a6f29cc2.jpg)
