### ISSUE TITLE
Viewing 'Oaks' featuretype in 1972 causes crash

### ISSUE THREAD

**Issue by davidheyman** [axismaps/rice#62]
Uncaught Error: Attempted to load an infinite number of tiles

**Comment by awoodruff** [comment]
This is caused by bad geometry, maybe specific to the Oaks data, throwing Leaflet `getBounds()` out of whack. There's a point with `coordinates:
 [-1.79769e+308,-1.79769e+308]`. Besides maybe fixing whatever that point is, it may be good to do some kind of bounds check either on the server or client side.
